name: Check
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: actions/checkout@v4
        with:
          repository: 9001/copyparty
          ref: 4e318d516531e6a9c683b21e58b9cb48131eb175
          path: work/copyparty
      - run: pip install jinja2
      - run: npm test
        env:
          COPYPARTY_SOURCE: ${{ github.workspace }}/work/copyparty
      - run: npm run build
      - run: docker build -t partyfinder:test .
